name = "ADIOS2"
uuid = "e0ce9d3b-0dbd-416f-8264-ccca772f60ec"
authors = ["Erik Schnetter <schnetter@gmail.com>"]
version = "0.3.0"

[deps]
ADIOS2_jll = "44b1415a-b224-5c99-9168-ff4febb5f37f"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ADIOS2_jll = "2.7.1"
MPI = "0.17, 0.18"
julia = "1.4"
